import { DocsClient } from '@/components/docs-client';
import { SectionPage } from '@/components/section-page';
import { getDocs, getProjects } from '@/lib/data';

export default function DocsPage() {
  const docs = getDocs();
  const projects = getProjects().map((project) => project.name);

  return (
    <SectionPage currentPath="/docs" title="Docs" subtitle="Architecture notes, specs, runbooks, and project docs generated by the system.">
      <DocsClient initialDocs={docs} projects={projects} />
    </SectionPage>
  );
}
