import Link from 'next/link';
import { SectionPage } from '@/components/section-page';
import { docs } from '@/lib/data';

export default function DocsPage() {
  return (
    <SectionPage currentPath="/docs" title="Docs" subtitle="Architecture notes, specs, runbooks, and project docs generated by the system.">
      <div className="stack">
        {docs.map((doc) => (
          <div className="card" key={doc.id}>
            <div className="panelTitle"><h3>{doc.title}</h3><span className="pill">{doc.type}</span></div>
            <div className="muted">Updated {doc.updated}{doc.project ? ` • Project: ${doc.project}` : ''}</div>
            <p>{doc.summary}</p>
            <Link href="/projects" className="muted">Open related project →</Link>
          </div>
        ))}
      </div>
    </SectionPage>
  );
}
